use crate::compiler::lexer::tokens::{Keyword, Operator, TokenGut};
use std::fmt;

impl fmt::Display for TokenGut {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            TokenGut::Keyword(k) => match k {
                Keyword::If => write!(f, "if"),
                Keyword::Else => write!(f, "else"),
                Keyword::Match => write!(f, "match"),
                Keyword::Case => write!(f, "case"),
                Keyword::Then => write!(f, "then"),
                Keyword::Do => write!(f, "do"),
                Keyword::While => write!(f, "while"),
                Keyword::For => write!(f, "for"),
                Keyword::In => write!(f, "in"),
                Keyword::Break => write!(f, "break"),
                Keyword::Continue => write!(f, "continue"),
                Keyword::Return => write!(f, "return"),
                Keyword::As => write!(f, "as"),
                Keyword::Let => write!(f, "let"),
                Keyword::And => write!(f, "and"),
                Keyword::Try => write!(f, "try"),
                Keyword::Catch => write!(f, "catch"),
                Keyword::Finally => write!(f, "finally"),
                Keyword::Throw => write!(f, "throw"),
                Keyword::Shape => write!(f, "shape"),
                Keyword::BindDef => write!(f, "bind"),
                Keyword::Operation => write!(f, "operation"),
                Keyword::Coerce => write!(f, "coerce"),
                Keyword::Prefix => write!(f, "prefix"),
                Keyword::Infix => write!(f, "infix"),
                Keyword::Postfix => write!(f, "postfix"),
                Keyword::Module => write!(f, "module"),
                Keyword::Use => write!(f, "use"),
                Keyword::Export => write!(f, "export"),
            },
            TokenGut::Operator(op) => match op {
                Operator::Add => write!(f, "+"),
                Operator::Sub => write!(f, "-"),
                Operator::Mul => write!(f, "*"),
                Operator::Div => write!(f, "/"),
                Operator::Mod => write!(f, "%"),
                Operator::Pow => write!(f, "**"),
                Operator::IntDiv => write!(f, "//"),
                Operator::BitAnd => write!(f, "&"),
                Operator::BitOr => write!(f, "|"),
                Operator::BitXor => write!(f, "^"),
                Operator::BitNot => write!(f, "~"),
                Operator::BitShiftLeft => write!(f, "<<"),
                Operator::BitShiftRight => write!(f, ">>"),
                Operator::Assign => write!(f, "="),
                Operator::Eq => write!(f, "=="),
                Operator::Teq => write!(f, "==="),
                Operator::Neq => write!(f, "!="),
                Operator::Gt => write!(f, ">"),
                Operator::Lt => write!(f, "<"),
                Operator::Gte => write!(f, ">="),
                Operator::Lte => write!(f, "<="),
                Operator::And => write!(f, "&&"),
                Operator::Or => write!(f, "||"),
                Operator::Question => write!(f, "?"),
                Operator::Exclamation => write!(f, "!"),
                Operator::Colon => write!(f, ":"),
                Operator::DoubleColon => write!(f, "::"),
                Operator::Dot => write!(f, "."),
                Operator::Arrow => write!(f, "->"),
                Operator::DoubleArrow => write!(f, "=>"),
                Operator::AddAssign => write!(f, "+="),
                Operator::SubAssign => write!(f, "-="),
                Operator::MulAssign => write!(f, "*="),
                Operator::DivAssign => write!(f, "/="),
                Operator::ModAssign => write!(f, "%="),
                Operator::BitAndAssign => write!(f, "&="),
                Operator::BitOrAssign => write!(f, "|="),
                Operator::BitXorAssign => write!(f, "^="),
                Operator::BitShiftLeftAssign => write!(f, "<<="),
                Operator::BitShiftRightAssign => write!(f, ">>="),
                Operator::Increment => write!(f, "++"),
                Operator::Decrement => write!(f, "--"),
                Operator::Comma => write!(f, ","),
            },
            _ => {
                write!(f, "_")
            }
        }
    }
}
